### ISSUE TITLE
HOWTO to compile 

### ISSUE THREAD

**Issue by ameen-mcmxc** [ofalk/libdnet#84] opened 2023-03-29 19:42 UTC
There is no instruction on how to compile it and run it on the target machine.
./configure fails with the below error :
"configure: error: cannot find required auxiliary files: compile"

**Comment by ofalk** [comment] 2023-04-06 07:45
Duplicate of #83

**Comment by ofalk** [comment] 2023-04-06 07:45
Thanks for reporting @ameen-mcmxc - but this is already handled in #83

**Closed as completed by ofalk** 2023-04-06 07:45 UTC
